#!/bin/sh
#
# spider script for synchronizing a documents directoy with text/html-file store for indexing with zettair
# requirements:
#  clone     -- for hard linking the store to a temperary directory
#  pdftotext -- for converting PDF to bare HTML files (tool in the poppler package)
#  iconv     -- for converting UTF-8 to ISO-8859-1
#  zet       -- for indexing (tool in the zettair package)


export LANG="en_US.UTF-8"
export MM_CHARSET="UTF-8"

DOCUMENTS_DIR="$1"
if [ ! -d "$DOCUMENTS_DIR" ]; then
   echo "The documents directory does not exist"
   exit
fi

ZETTAIR_DIR="/var/db/zettair"
if [ ! -d "$ZETTAIR_DIR" ]; then
   echo "The directory which holds the Zettair search index does not exist"
   exit
fi

cd "$ZETTAIR_DIR"

if [ ! -e "token" ] && [ "$2" != "force" ] || [ -e "running" ]; then
   if [ "$2" == "force" ]; then
      echo "$0 is running already."
   else
      exit
   fi
else
   touch "running"
   rm -f "token"
fi

if [ -d "changes" ] && [ -d "texthtml" ]; then
   /usr/bin/find "changes" -links 2 -and \! -type d -print0 | xargs -0 rm -v >/dev/null 2>&1
else
   rm -rf "changes" "texthtml"
   /usr/local/bin/clone -lv0 "$DOCUMENTS_DIR" "changes"
   mkdir -p "texthtml"
fi

cd "changes"

htmlist=$(
   /usr/bin/find . -name "*.html" \
   | while read -r fname ; do
      if [ -e "$DOCUMENTS_DIR/$fname" ] ; then
         /usr/bin/iconv -s -f UTF-8 -t ISO-8859-1//TRANSLIT//IGNORE "$DOCUMENTS_DIR/$fname" > "../texthtml/$fname.iso.html"
         echo "texthtml/$fname.iso.html"
      else
         rm -f "../texthtml/$fname.iso.html"
      fi
   done
)
if [ "$htmlist" != "" ] ; then
   htmlist="$htmlist"$'\n'
fi

pdflist=$(
   /usr/bin/find . -iname "*.pdf" \
   | while read -r fname ; do
      if [ -e "$DOCUMENTS_DIR/$fname" ] ; then
         /usr/local/bin/pdftotext -enc Latin1 -htmlmeta "$DOCUMENTS_DIR/$fname" "../texthtml/$fname.iso.html"
         echo "texthtml/$fname.iso.html"
      else
         rm -f "../texthtml/$fname.iso.html"
      fi
   done
)
if [ "$pdflist" != "" ] ; then
   pdflist="$pdflist"$'\n'
fi

txtlist=$(
   /usr/bin/find . -iname "*.txt" \
   | while read -r fname ; do
      if [ -e "$DOCUMENTS_DIR/$fname" ] ; then
         echo "<HTML><BODY>" > "../texthtml/$fname.iso.html"
         /usr/bin/iconv -s -f UTF-8 -t ISO-8859-1//TRANSLIT//IGNORE "$DOCUMENTS_DIR/$fname" >> "../texthtml/$fname.iso.html"
         echo "</BODY></HTML>" >> "../texthtml/$fname.iso.html"
         echo "texthtml/$fname.iso.html"
      else
         rm -f "../texthtml/$fname.iso.html"
      fi
   done
)
if [ "$txtlist" != "" ] ; then
   txtlist="$txtlist"$'\n'
fi

rtflist=$(
   /usr/bin/find . -iname "*.rtf" -or -iname "*.rtfd.zip" \
   | while read -r fname ; do
      if [ -e "$DOCUMENTS_DIR/$fname" ] ; then
         /usr/local/bin/rtftotext.py "$DOCUMENTS_DIR/$fname" > "../texthtml/$fname.iso.html"
         echo "texthtml/$fname.iso.html"
      else
         rm -f "../texthtml/$fname.iso.html"
      fi
   done
)
if [ "$rtflist" != "" ] ; then
   rtflist="$rtflist"$'\n'
fi

doclist=$(
   /usr/bin/find . -iname "*.docx" \
   | while read -r fname ; do
      if [ -e "$DOCUMENTS_DIR/$fname" ] ; then
         /usr/local/bin/docxtotext.py "$DOCUMENTS_DIR/$fname" > "../texthtml/$fname.iso.html"
         echo "texthtml/$fname.iso.html"
      else
         rm -f "../texthtml/$fname.iso.html"
      fi
   done
)
if [ "$doclist" != "" ] ; then
   doclist="$doclist"$'\n'
fi

pptlist=$(
   /usr/bin/find . -iname "*.pptx" \
   | while read -r fname ; do
      if [ -e "$DOCUMENTS_DIR/$fname" ] ; then
         /usr/local/bin/pptxtotext.py "$DOCUMENTS_DIR/$fname" > "../texthtml/$fname.iso.html"
         echo "texthtml/$fname.iso.html"
      else
         rm -f "../texthtml/$fname.iso.html"
      fi
   done
)
if [ "$pptlist" != "" ] ; then
   pptlist="$pptlist"$'\n'
fi

xlslist=$(
   /usr/bin/find . -iname "*.xlsx" \
   | while read -r fname ; do
      if [ -e "$DOCUMENTS_DIR/$fname" ] ; then
         /usr/local/bin/xlsxtotext.py "$DOCUMENTS_DIR/$fname" > "../texthtml/$fname.iso.html"
         echo "texthtml/$fname.iso.html"
      else
         rm -f "../texthtml/$fname.iso.html"
      fi
   done
)
if [ "$xlslist" != "" ] ; then
   xlslist="$xlslist"$'\n'
fi

cd ..
rm -rf changes
/usr/local/bin/clone -lv0 "$DOCUMENTS_DIR" "changes"

rm -f index*
echo "$htmlist$pdflist$txtlist$rtflist$doclist$pptlist$xlslist" | /usr/local/bin/zet -i >/dev/null 2>&1
rm -f running
