#!/bin/sh
#
# spider script for synchronizing a remote site with a local store for indexing with zettair
# requirements:
#  clone     -- for hard linking the store to a temperary directory
#  wget 1.18 -- for synchronizing the remote site with the local store
#  pdftotext -- for converting PDF to bare HTML files (tool in the poppler package)
#  iconv     -- for converting UTF-8 to ISO-8859-1
#  zet       -- for indexing (tool in the zettair package)

#  Installation of wget 1.18 -- the spider mode of wget 1.19 and above is incompatible beyond repair
#  cd ~/install
#  fetch https://ftp.gnu.org/gnu/wget/wget-1.18.tar.gz
#  tar -oxzf wget-1.18.tar.gz
#  cd wget-1.18
#  ./configure --enable-threads=posix --with-ssl=openssl --with-libssl-prefix=/usr/lib
#  make install clean
#  cd ..; rm -r wget-1.18


export LANG="en_US.UTF-8"
export MM_CHARSET="UTF-8"

cd /var/db/psindex

if [ ! -e token ] && [ "$1" != "force" ] || [ -e running ]; then
   if [ "$1" == "force" ]; then
      echo "$0 is running already."
   else
      exit
   fi
else
   touch running
   rm -f token
fi

URI="http://localhost:8/forums.php"
DIR="projectstore.net"
TMP="temp"

if [ -d "$DIR" ]; then
   /usr/local/bin/clone -ydlv0 "$DIR" "$TMP"
   xcllist=`/usr/local/bin/wget --spider -r -l inf -N -e robots=off -P "$TMP" -nH "$URI" 2>&1 >/dev/null \
            | /usr/bin/sed -n "/^Server file no newer than local file ‘"$TMP"/{s//"$DIR"/;s/’ \-\- not retrieving\.$//;p;}"`
   /usr/bin/find "$DIR" -links 2 -and \! -type d -and \! -name "*.iso.html" -print0 | xargs -0 rm -v \
   | while read fname ; do
      # this won't delete mid=X.iso.html files
      rm -f "$fname.iso.html"
   done
   rm -rf "$TMP"
else
   xcllist=""
fi

/usr/local/bin/wget -q -r -l inf -N -e robots=off -P "$DIR" -nH "$URI"

htmlist=$(
   /usr/bin/find "$DIR" -name "*.html" -and \! -name "*.iso.html" \
   | while read -r fname ; do
      echo "$xcllist" | /usr/bin/grep -q "$fname"
      if [ $? -gt 0 ] || [ ! -e "$fname.iso.html" ]; then
         /usr/bin/iconv -s -f UTF-8 -t ISO-8859-1//TRANSLIT//IGNORE "$fname" > "$fname.iso.html"
      fi
      echo "$fname.iso.html"
   done
)
if [ "$htmlist" != "" ] ; then
   htmlist="$htmlist"$'\n'
fi

pdflist=$(
   /usr/bin/find "$DIR" -iname "*.pdf" \
   | while read -r fname ; do
      echo "$xcllist" | /usr/bin/grep -q "$fname"
      if [ $? -gt 0 ] || [ ! -e "$fname.iso.html" ]; then
         /usr/local/bin/pdftotext -enc Latin1 -htmlmeta "$fname" "$fname.iso.html"
      fi
      echo "$fname.iso.html"
   done
)
if [ "$pdflist" != "" ] ; then
   pdflist="$pdflist"$'\n'
fi

txtlist=$(
   /usr/bin/find "$DIR" -iname "*.txt" \
   | while read -r fname ; do
      echo "$xcllist" | /usr/bin/grep -q "$fname"
      if [ $? -gt 0 ] || [ ! -e "$fname.iso.html" ]; then
         echo "<HTML><BODY>" > "$fname.iso.html"
         /usr/bin/iconv -s -f UTF-8 -t ISO-8859-1//TRANSLIT//IGNORE "$fname" >> "$fname.iso.html"
         echo "</BODY></HTML>" >> "$fname.iso.html"
      fi
      echo "$fname.iso.html"
   done
)
if [ "$txtlist" != "" ] ; then
   txtlist="$txtlist"$'\n'
fi

rtflist=$(
   /usr/bin/find "$DIR" -iname "*.rtf" -or -iname "*.rtfd.zip" \
   | while read -r fname ; do
      echo "$xcllist" | /usr/bin/grep -q "$fname"
      if [ $? -gt 0 ] || [ ! -e "$fname.iso.html" ]; then
         /usr/local/bin/rtftotext.py "$fname" > "$fname.iso.html"
      fi
      echo "$fname.iso.html"
   done
)
if [ "$rtflist" != "" ] ; then
   rtflist="$rtflist"$'\n'
fi

doclist=$(
   /usr/bin/find "$DIR" -iname "*.docx" \
   | while read -r fname ; do
      echo "$xcllist" | /usr/bin/grep -q "$fname"
      if [ $? -gt 0 ] || [ ! -e "$fname.iso.html" ]; then
         /usr/local/bin/docxtotext.py "$fname" > "$fname.iso.html"
      fi
      echo "$fname.iso.html"
   done
)
if [ "$doclist" != "" ] ; then
   doclist="$doclist"$'\n'
fi

pptlist=$(
   /usr/bin/find "$DIR" -iname "*.pptx" \
   | while read -r fname ; do
      echo "$xcllist" | /usr/bin/grep -q "$fname"
      if [ $? -gt 0 ] || [ ! -e "$fname.iso.html" ]; then
         /usr/local/bin/pptxtotext.py "$fname" > "$fname.iso.html"
      fi
      echo "$fname.iso.html"
   done
)
if [ "$pptlist" != "" ] ; then
   pptlist="$pptlist"$'\n'
fi

xlslist=$(
   /usr/bin/find "$DIR" -iname "*.xlsx" \
   | while read -r fname ; do
      echo "$xcllist" | /usr/bin/grep -q "$fname"
      if [ $? -gt 0 ] || [ ! -e "$fname.iso.html" ]; then
         /usr/local/bin/xlsxtotext.py "$fname" > "$fname.iso.html"
      fi
      echo "$fname.iso.html"
   done
)
if [ "$xlslist" != "" ] ; then
   xlslist="$xlslist"$'\n'
fi

msglist=$(
   /usr/bin/find "$DIR" -name "message.php?mid*" \
   | while read fname ; do
      isoname="$DIR/"`echo "$fname" | /usr/bin/sed "s|$DIR/message.php?||"`".iso.html"
      echo "$xcllist" | /usr/bin/grep -q "$fname"
      if [ $? -gt 0 ] || [ ! -e "$isoname" ]; then
         /usr/bin/iconv -s -f UTF-8 -t ISO-8859-1//TRANSLIT//IGNORE "$fname" > "$isoname"
      fi
      echo "$isoname"
   done
)

rm -f index*
echo "$htmlist$pdflist$txtlist$rtflist$doclist$pptlist$xlslist$msglist" | /usr/local/bin/zet -i >/dev/null 2>&1

rm -f running
