#!/bin/sh
#
# spider script for synchronizing a reomte site with a local store for indexing with zettair
# requirements:
#  clone     -- for hard linking the store to a temperary directory
#  wget      -- for synchronizing the remote site with the local store
#  pdftotext -- for converting PDF to bare HTML files (tool in the poppler package)
#  iconv     -- for converting UTF-8 to ISO-8859-1
#  zet       -- for indexing (tool in the zettair package)

cd /var/db/psindex

if ! [ -e token ]; then
   exit
else
   rm -f token
fi

LANG="en_US.UTF-8"

URI="http://localhost:8/forums.php"
DIR="projectstore.net"
TMP="temp"

if [ -d "$DIR" ]; then
   /usr/local/bin/clone -ydlv0 "$DIR" "$TMP"
   xcllist=`/usr/local/bin/wget --spider -r -l inf -N -e robots=off -P "$TMP" -nH "$URI" 2>&1 >/dev/null \
            | /usr/bin/sed -n "/^Server file no newer than local file ‘"$TMP"/{s//"$DIR"/;s/’ \-\- not retrieving\.$//;p;}"`
   /usr/bin/find "$DIR" -links 2 -and \! -type d -and \! -name "*.iso.html" -print0 | xargs -0 rm -v \
   | while read fname ; do
      # this won't delete mid=X.iso.html files
      rm -f "$fname.iso.html"
   done
   rm -rf "$TMP"
else
   xcllist=""
fi

/usr/local/bin/wget -q -r -l inf -N -e robots=off -P "$DIR" -nH "$URI"

htmlist=$(
   /usr/bin/find "$DIR" -name "*.html" -and \! -name "*.iso.html" \
   | while read -r fname ; do
      echo "$xcllist" | /usr/bin/grep -q "$fname"
      if [ $? -gt 0 ] || ! [ -e "$fname.iso.html" ]; then
         /usr/bin/iconv -s -f UTF-8 -t ISO-8859-1//TRANSLIT//IGNORE "$fname" > "$fname.iso.html"
      fi
      echo "$fname.iso.html"
   done
)
if [ "$htmlist" != "" ] ; then
   htmlist="$htmlist"$'\n'
fi

pdflist=$(
   /usr/bin/find "$DIR" -name "*.pdf" \
   | while read -r fname ; do
      echo "$xcllist" | /usr/bin/grep -q "$fname"
      if [ $? -gt 0 ] || ! [ -e "$fname.iso.html" ]; then
         /usr/local/bin/pdftotext -enc Latin1 -htmlmeta "$fname" "$fname.iso.html"
      fi
      echo "$fname.iso.html"
   done
)
if [ "$pdflist" != "" ] ; then
   pdflist="$pdflist"$'\n'
fi

msglist=$(
   /usr/bin/find "$DIR" -name "message.php?mid*" \
   | while read fname ; do
      iname="$DIR/"`echo "$fname" | /usr/bin/sed "s|$DIR/message.php?||"`".iso.html"
      echo "$xcllist" | /usr/bin/grep -q "$fname"
      if [ $? -gt 0 ] || ! [ -e "$iname" ]; then
         /usr/bin/iconv -s -f UTF-8 -t ISO-8859-1//TRANSLIT//IGNORE "$fname" > "$iname"
      fi
      echo "$iname"
   done
)

rm -f index*
echo "$htmlist$pdflist$msglist" | /usr/local/bin/zet -i >/dev/null 2>&1

